export const DEMO = {
    BLANK_LINK: "#!",
    LOGOUT: "/signin",
    HOME: "/home",
    TRAN: "/transactions",
};

export const ACT_SET_TRAN_LIST = 'ACT_SET_TRAN_LIST';
export const ACT_SET_CHART_TRAN_LIST = 'ACT_SET_CHART_TRAN_LIST';

export const ACT_SET_CHART_TRAN_LIST1 = 'ACT_SET_CHART_TRAN_LIST1';

export const ACT_SET_LIGAS_NET_DEBIT = 'ACT_SET_LIGAS_NET_DEBIT';
export const ACT_SET_EKOOP_NET_DEBIT = 'ACT_SET_EKOOP_NET_DEBIT';
export const ACT_SET_MASSSPEC_NET_DEBIT = 'ACT_SET_MASSSPEC_NET_DEBIT';
export const ACT_SET_PFCCO_NET_DEBIT = 'ACT_SET_PFCCO_NET_DEBIT';
export const ACT_SET_SG_NET_DEBIT = 'ACT_SET_SG_NET_DEBIT';

export const ACT_SET_SUMBER_NET_DEBIT = 'ACT_SET_SUMBER_NET_DEBIT';
export const ACT_SET_PANUCR_NET_DEBIT = 'ACT_SET_PANUCR_NET_DEBIT';
export const ACT_SET_TAKERA_NET_DEBIT = 'ACT_SET_TAKERA_NET_DEBIT';
export const ACT_SET_SKK_NET_DEBIT = 'ACT_SET_SKK_NET_DEBIT';